language: android
jdk: oraclejdk8
android:
  components:
      - tools
      - build-tools-26.0.1
      - android-26
      - extra
      - extra-android-m2repository
      - extra-google-m2repository
licenses:
      - android-sdk-license-.+
script:
  - ./gradlew build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
